### ISSUE TITLE
🚀 Editor 조사 및 선정

### ISSUE THREAD

**Issue by dmdmdkdkr** [boostcampwm2023/web12-algo-with-me#11]
## 구현해야하는 기능
- Monaco, CodeMirror, Ace 에디터 조사 및 학습정리
- 위 내용을 팀원들과 공유 후 선정(CodeMirror)

## 관련 링크
- Monaco Editor
https://microsoft.github.io/monaco-editor/
- CodeMirror Editor
https://codemirror.net/
- Ace Editor
https://ace.c9.io/
- 에디터 비교 정리
https://glacier-aura-f95.notion.site/Editor-d74acb8ac6014dcfbc16357f36ec4e06?pvs=4

**Comment by dev2820** [comment]
의사결정

https://www.notion.so/Editor-9a028a4ed8d4490da66cd1ed0dd215cb?pvs=4
