### ISSUE TITLE
🛠 환경변수 파일 읽기 안되는 문제 해결

### ISSUE THREAD

**Issue by rladydgn** [boostcampwm2023/web12-algo-with-me#116]
## 버그 설명
nest dotenv를 사용해 환경변수 파일을 읽는데 늦게 불러와져서 환경변수를 읽지 못하는 문제가 종종 발생하고 있습니다.

## 예상하는 해결 방법
- 환경변수 불러오는 모듈이 가장먼저 실행되게 한다.
- 다른 방법을 생각해 봐야 할것같습니다.

**Comment by yechan2468** [comment]
배포 환경에서는 도커를 사용하므로, docker compose를 통해 미리 환경변수를 넣어주면 문제가 해결됨이 확인되었습니다.
이후 하드코딩했던 부분들을 process.env.*로 고쳐줘야 하겠지만, 프로젝트 진행에 크리티컬하게 방해가 될 정도는 아니므로 close합니다.
