### ISSUE TITLE
🛠 1차 데모 버그 픽스

### ISSUE THREAD

**Issue by dev2820** [boostcampwm2023/web12-algo-with-me#234]
## 버그 설명

1차 데모에서 발견한 자잘한 버그를 수정한다.
각 버그는 이 이슈에 댓글로 달 예정

## 버그 재현 방법
> 스크린 샷 등을 첨부해 버그를 어떻게 재현하는지 설명해 주세요

**Comment by mahwin** [comment]
테스트

**Comment by dev2820** [comment]
테스트 코멘트 작성

**Comment by dmdmdkdkr** [comment]
테스트

**Comment by dev2820** [comment]
## 버그 설명
대회 생성하기 버튼이 아니라 버튼 안의 텍스트를 눌러야 링크 이동이 된다.
<img width="181" alt="스크린샷 2023-12-07 오후 3 34 02" src="https://github.com/boostcampwm2023/web12-algo-with-me/assets/40891497/120817e7-8ff6-4268-88ea-45f29fca96c8">
저기서 가운데 텍스트 영역을 클릭 해야만 이동이 됨

## 문제 원인
가운데 텍스트에만 링크가 걸려있다. 텍스트가 아니라 버튼을 링크로 감싸야함

**Comment by mahwin** [comment]
### 버그 설명

대회 생성하고 대회 정보 가져오기가 안됨
링크가 요래 됨 (https://www.algo-with-me.site/contest/detail/undefined)

![스크린샷 2023-12-07 오후 3 47 18](https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/9682432e-1d40-4815-972d-c9ee6d6623db)

### 문제 원인

**Comment by mahwin** [comment]
### 문제 상세 보기 페이지

![스크린샷 2023-12-07 오후 5 12 42](https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/441f1276-bc87-49be-bdc8-8e58efeff105)

### 문제 원인
- 예전 url을 사용하고 있었음.

### 해결  완료

**Comment by mahwin** [comment]
대회 상세보기 페이지에 참여인원/최대 참여인원이 없음  변경 완료

**Comment by mahwin** [comment]
Chip 보더 컬러 이상하게 들어간 것 수정
