### ISSUE TITLE
🛠 1차 데모 버그 픽스 2

### ISSUE THREAD

**Issue by dev2820** [boostcampwm2023/web12-algo-with-me#257]
## 버그 설명

1차 데모에서 발견된 버그를 수정한다. (2회차)

## 버그 재현 방법
> 스크린 샷 등을 첨부해 버그를 어떻게 재현하는지 설명해 주세요

## 관련 링크

https://www.notion.so/1-4c1c78b356e44db19e09fec4821a504b?pvs=4

**Comment by dmdmdkdkr** [comment]
### 대시보드
- 대시보드 모달 보더 레디우스 수정
- 대시보드 모달 myRank 차별화

**Comment by mahwin** [comment]
### 해야할 일
메인 페이지 대시보드 링크 
- 메인 페이지 대시보드 링크가 해당 대회 대회 화면으로 연결되는 오류 해결

**Comment by mahwin** [comment]
### 해야할 일
메인 페이지 테이블 row 라인 넣기

**Comment by mahwin** [comment]
### 한 일
- 메인 페이지 테이블 시간 디자인 수정

**Comment by mahwin** [comment]
### 한 일
- 대회 상세페이지  내의 대회 참여 버튼 로직 제대로 작동하게 변경

**Comment by mahwin** [comment]
### 한 일
- 모달에  보더 레디어스 넣음

**Comment by mahwin** [comment]
### 한 일

- 대시보드 테이블 my Rank  부분 강조 추가

**Comment by dmdmdkdkr** [comment]
### 한 일
- 대회가 종료되면 대회 상세 페이지로 이동

**Comment by dmdmdkdkr** [comment]
### 한 일
- 채점중에는 다시 제출할 수 없도록 작성
