### ISSUE TITLE
🛠 버그 수정 3차

### ISSUE THREAD

**Issue by dev2820** [boostcampwm2023/web12-algo-with-me#261]
## 버그 재현 방법
> 스크린 샷 등을 첨부해 버그를 어떻게 재현하는지 설명해 주세요

**Comment by mahwin** [comment]
### 한 일
- 대회 페이지 내의 대시보드 모달에 스크롤 추가

![Image](https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/48628057-ce39-4584-95cd-4129c830f55a)

**Comment by mahwin** [comment]
### 한 일

- 코드 초기화 버튼
- 문제 선택 aside 에 색상 적용 

![Image](https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/0d163a1b-c464-469e-8358-cf7b78354142)

**Comment by mahwin** [comment]
### 한 일

- 로그인 페이지  디자인 수정

![스크린샷 2023-12-09 오전 12 40 37](https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/f16ec4b1-d856-4d0b-b13f-e947a3e087c5)

**Comment by mahwin** [comment]
### 한 일

- 문제 페이지 디자인 변경

![Image](https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/4a52a693-d91c-42af-b435-14bc86499551)

**Comment by mahwin** [comment]
### 한 일 

- 대시보드 집계 loading 화면에 Header 추가
