### ISSUE TITLE
🚀 api 서버에서 채점 결과 받아서 client에게 전송하는 것 구현

### ISSUE THREAD

**Issue by rladydgn** [boostcampwm2023/web12-algo-with-me#45]
## 구현해야하는 기능
- 채점서버에서 테스트 케이스 채점 끝나면 호출할 api 구현
- 호출하고 나서 db 저장 및 websocket을 통해 결과 전송하는 기능 구현

**Comment by yechan2468** [comment]
PR 머지됨
