### ISSUE TITLE
🚀 채점용 docker image 구현

### ISSUE THREAD

**Issue by rladydgn** [boostcampwm2023/web12-algo-with-me#6]
## 구현해야하는 기능

- 자바스크립트 코드와 테스트케이스 입/출력값을 입력으로 받아, 코드의 실행 결과값을 return하는 프로그램 구현
- docker image로 build

---

지금은 docker run을 통해 node-alpine 이미지를 띄워 채점한 뒤 container가 stop된다.
docker를 서버로 만들어, 요청을 받아 코드 실행한 뒤 코드 실행이 끝나면 응답하는 방식으로 바꾸려고 한다.

- docker를 express 서버로 만들기
- docker의 코드 실행 api 만들기
- 코드 실행이 끝나면 채점서버에 api 요청 보내기

## 관련 링크

- [회의 - BE 채점서버 아키텍처 관련 회의](https://www.notion.so/BE-0efb2000a49b454098e8b897a757d537?pvs=4)

**Comment by yechan2468** [comment]
PR 머지됨
